name: "[简体中文] 报告漏洞/问题"
description: "向我们报告漏洞/问题以让Trapdoor变得更好"
labels: ["bug"]
body:

- type: input
  id: trversion
  attributes:
    label: trapdoor版本号版本
    description: |
      请输入一个完整的版本号,如`0.15-1.19.10.03`,如果插件是从
      actions下载的，请填写action运行ID(#开头)或者commit hash
  validations:
    required: true

- type: input
  id: llversion
  attributes:
    label: "LiteLoader版本"
  validations:
    required: true

- type: input
  id: bdsversion
  attributes:
    label: BDS版本
  validations:
    required: true

- type: textarea
  id: what-happened
  attributes:
    label: 发生了什么?
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: 复现此问题的步骤
    placeholder: |
      1. Do something
      2. ...
      3. ...
